cranelift/codegen/src/isa/zkasm/inst/emit_tests.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs

zkASM: restore `Inst::Mov` tests

---

cranelift/codegen/src/isa/zkasm/docs/README.md

I'm aiming to migrate the documentation from https://hackmd.io/IqQMg6I6Qz-AEc8MSEU4eg?view to GitHub, this is a first step.

Add a README for zkASM backend

---

cranelift/codegen/src/isa/zkasm/docs/architecture.md

A missing newline caused the markdown to not be generated properly.

[docs] fix a minor markdown issue

---

cranelift/codegen/src/isa/zkasm/abi.rs
cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/emit_tests.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/zkasm_data/generated/add.zkasm
cranelift/zkasm_data/generated/add_func.zkasm
cranelift/zkasm_data/generated/counter.zkasm
cranelift/zkasm_data/generated/fibonacci.zkasm
cranelift/zkasm_data/generated/locals.zkasm
cranelift/zkasm_data/generated/locals_simple.zkasm

Since now we're looking at supporting an architecture with stack growth in an unusual direction, it is better to be intentional about what semantic purpose these have, and having them as separate instructions makes it somewhat easier to think about this.

zkasm: split AdjustSp to separate variants for Reserve and Release stack space

---

cranelift/codegen/src/isa/zkasm/abi.rs

Given that stack opeerates in numbers of aligned slots, rather then bytes, making sure that the stack is aligned to 8 bytes can’t be more wrong than aligning it to 1.

zkasm: stack alignment is 8 bytes

---

.github/workflows/main.yml
cranelift/codegen/src/isa/zkasm/abi.rs
cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/emit_tests.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/zkasm_data/generated/add.zkasm
cranelift/zkasm_data/generated/add_func.zkasm
cranelift/zkasm_data/generated/counter.zkasm
cranelift/zkasm_data/generated/fibonacci.zkasm
cranelift/zkasm_data/generated/locals.zkasm
cranelift/zkasm_data/generated/locals_simple.zkasm

Best reviewd commit-by-commit. The previous failures turned out to be due to extra `stack_size = stack_size / 8` computation in the prologue/epilogue generation. I however took an opportunity to fix up the register clobbering code in general. In particular, I took a conservative approach of specifying all registers other than A as callee-saved in order to ensure we don’t rely on accidental behaviours this enables. For A I filed https://github.com/near/wasmtime/issues/45 instead, as doing otherwise makes our tests break for the time being.
You will also notice that I fixed the computation of the stack offsets: our stack pointer goes upwards, so once we reserve some space (`SP + 1 => SP`) we must access slots *below* that reserved space, so the first slot we can write to is actually at `SP …

zkasm: improve handling of register clobbering and prologue/epilogue generation

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/args.rs
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/codegen/src/isa/zkasm/inst/regs.rs
cranelift/codegen/src/isa/zkasm/lower.isle
cranelift/filetests/src/test_zkasm.rs
cranelift/zkasm_data/div.wat
cranelift/zkasm_data/generated/div.zkasm
cranelift/zkasm_data/generated/i64_div.zkasm
cranelift/zkasm_data/i64_div.wat

Signed division via arith for i32 and i64

Signed division via Arith

---

ci/test-zk.sh
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/filetests/src/test_zkasm.rs
cranelift/zkasm_data/_should_fail_unreachable.wat
cranelift/zkasm_data/generated/_should_fail_unreachable.zkasm
cranelift/zkasm_data/generated/nop.zkasm
cranelift/zkasm_data/nop.wat

Unreachable + test for nop + testing of files that should fail in CI. I didn't find any opcode in zkasm which perform analogue of ``unreachable`` in wasm, so just write UNREACHABLE in zkasm code, interpreter of zkasm clearly shows that error is in this line.

Unreachable + nop

---

Cargo.lock
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/filetests/Cargo.toml
cranelift/filetests/filetests/isa/zkasm/add.clif
cranelift/filetests/src/test_compile.rs

This changeset begins the process of dropping the ad-hoc test framework we had built for ourselves and instead adding the necessary support for zkasm needs into the filetest framework that cranelift had in the first place.
Among other things this will eventually allow us to use `clif-tool` to easily run ad-hoc test cases and integrate alright with the rest of the tooling as well.

filetest: allow filetests to work for targets without disassembler

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/codegen/src/isa/zkasm/lower.isle
cranelift/codegen/src/isa/zkasm/lower/isle.rs
cranelift/filetests/filetests/isa/zkasm/add.clif
cranelift/filetests/src/test_zkasm.rs
cranelift/zkasm_data/div.wat
cranelift/zkasm_data/generated/i32_const.zkasm
cranelift/zkasm_data/generated/i64_const.zkasm
cranelift/zkasm_data/generated/i64_div.zkasm
cranelift/zkasm_data/generated/i64_mul.zkasm
cranelift/zkasm_data/generated/rem.zkasm
cranelift/zkasm_data/i32_const.wat
cranelift/zkasm_data/i64_const.wat
cranelift/zkasm_data/rem.wat

Add support for ``rem`` opcode and fixes error in ``div`` opcode, when division lefts non-zero reminder

zkasm: rem

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/lower.isle

We won’t have any in our wasm MVP to the best of my knowledge and intuition.
NB: review the last commit only, as this is based on top of another PR.

Remove all code pertinent to 128-bit integers

---

ci/test-zk-64.sh

Otherwise bash just prints current settings and fails to set both `-x` and `-e`.

zkasm/ci: Fix set -eux typo

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/codegen/src/isa/zkasm/lower.isle

No test here as there isn’t really a wasm instruction that directly becomes `ineg`, except perhaps through optimizations. Best way to test this would be to have clift test instead, but we don’t have infrastructure for those targetting zkasm either.

zkasm: crude implementation of ineg

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/codegen/src/isa/zkasm/lower.isle

This is binary not (~x in C or !x in Rust.) WASM does not produce this specific instruction and lowers it to `xor` usually, but in zkasm it is better for us to use subtraction instead – as it is faster.
I believe this should produce equivalent results for all inputs.
Fixes https://github.com/near/wasmtime/issues/66

zkasm: implement lowering for bnot

---

.github/workflows/main.yml
.gitmodules
ci/test-zkasm.sh

This PR adds zkevm-proverjs as a submodule
This simplifies the development setup both locally and on CI, as we
don't need to clone zkevm-proverjs as an explicit step.
Given that we don't plan to directly merge back into wasmtime upstream, I think it's fine to deviate in more major ways from the existing test infrastructure if this gives us productivity gains.

Add zkevm-proverjs as a submodule

---

.github/workflows/main.yml
.gitignore
.gitmodules
ci/test-zkasm.sh
tests/zkasm/package-lock.json
tests/zkasm/package.json
tests/zkasm/run-tests-zkasm.js

The main purpose is to make testing .zkasm files simpler. This commit
introduces few improvements:
- Tests run significantly faster (under 1 second for all tests)
- Errors are easier to read
- We have ability to show detailed profiling information (number of steps)
You can see an example of output here: https://github.com/near/wasmtime/actions/runs/6895606111/job/18759917589?pr=89#step:4:1

Rewrite zkasm test infra to JS

---

tests/zkasm/package-lock.json
tests/zkasm/package.json

This makes sure we use 64bit branch for zkevm-proverjs. Thanks to @MCJOHN974 for catching this

Switch to 64bit proverjs

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/inst/mod.rs

The Lui is currently correctly replaced by `LoadConst*` instructions and `Auipc` is not really relevant to zkasm (I believe it is largely useful for relocations and loading data at locations further away than 20 or 12 bytes, whichever one it is.)

zkasm: remove Lui and Auipc code

---

.github/workflows/main.yml
ci/spectest-zkasm.sh
ci/zkasm-result.py
cranelift/codegen/src/isa/zkasm/docs/state.csv

Added script to generate ``.csv`` with spectest results and asserting commited result corresponds actual results in CI
Fixes #84

CI: spectests in CI

---

cranelift/codegen/src/isa/zkasm/docs/usage.md

As now we don't need to explicitly do `npm install`

Update usage of test-zkasm.sh

---

cranelift/codegen/src/isa/zkasm/inst.isle
cranelift/codegen/src/isa/zkasm/lower.isle
cranelift/codegen/src/isa/zkasm/lower/isle.rs
cranelift/filetests/src/test_zkasm.rs
cranelift/zkasm_data/generated/memory.zkasm
cranelift/zkasm_data/memory.wat
cranelift/zkasm_data/state.csv
docs/zkasm/test_summary.csv

This intermediate step makes ISLE rules support generating memory loads and stores. The test file `memory.wat` still fails because we need to correctly implement ZK ASM instruction generation.
The majority of the ISLE code is coming from RISC-V backend.

Add correct ISLE rules for memory operations

---

cranelift/codegen/src/isa/zkasm/inst/mod.rs
cranelift/zkasm_data/benchmarks/sha256/generated/from_rust.zkasm
cranelift/zkasm_data/benchmarks/sha256/state.csv

This is the last tweak to get SHA256 benchmark to compile.
It still crashes due to memory ops syntax error, but we'll fix that next.

Tweak worst case size

---

cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/zkasm_data/benchmarks/sha256/generated/from_rust.zkasm

When we use NominalSPOffset, we need to adjust it using `virtual_sp_offset`.
This is one of the changes that was needed to make SHA256 work (https://github.com/near/wasmtime/pull/185)

Account for virtual sp adjustments

---

cranelift/codegen/src/isa/zkasm/abi.rs
cranelift/codegen/src/isa/zkasm/inst/args.rs
cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/zkasm_data/benchmarks/sha256/generated/from_rust.zkasm

This is another change necessary to support SHA256 benchmark (https://github.com/near/wasmtime/pull/185).
Concretely, frame pointer access is used to read arguments to the function passed using stack when there are not enough registers.

Support loads and stores at FPOffset

---

cranelift/codegen/src/isa/zkasm/inst/emit.rs
cranelift/codegen/src/isa/zkasm/lower.isle
cranelift/codegen/src/isa/zkasm/lower/isle.rs
cranelift/zkasm_data/benchmarks/sha256/generated/from_rust.zkasm
cranelift/zkasm_data/generated/memory.zkasm
cranelift/zkasm_data/generated/memory_i32.zkasm

This removes the hacky implementation using LoadExtName in favor of a more targeted rule.
Note, that this is also an example where a rule for immediate addition would be useful and where the basic constant folding pass would not work. So https://github.com/near/wasmtime/issues/105 actually becomes quite appealing.

Add ISLE rule for heap offset symbol

---

tests/zkasm/package-lock.json
tests/zkasm/package.json

Code to run tests depends on `pilcom`:
https://github.com/near/wasmtime/blob/ca0d6dcefbb06ae259877cbec8b4aababa4e3134/tests/zkasm/run-tests-zkasm.js#L11
Though `pilcom` is not a dependency. This hasn’t surfaced since `zkevm-proverjs` depends on `pilcom`, so it is available anyway. The missing `pilcom` dependency poses a problem when using a local `zkevm-proverjs` for debugging (e.g. helper usage).
```
// package.json: use local `zkevm-proverjs`
"@0xpolygonhermez/zkevm-proverjs": "file:<path>",
```

fix: add missing `pilcom` dependency

---

cranelift/zkasm_data/benchmarks/sha256/from_rust.wat
cranelift/zkasm_data/benchmarks/sha256/generated/from_rust.zkasm

There are a few changes:
- Using `Sha256::digest` directly instead of creating a mutable hasher object
- Using `stack-size=2048` to change the memory address of the data region
- Simpler equality check of u8 arrays instead of chunked u64 integers
See the new code at: https://gist.github.com/akashin/89f2dd88ee267681f87882d27e428e55

Adjust SHA256 benchmark code

---

cranelift/codegen/src/isa/zkasm/inst/emit.rs

This makes it easy to see all missing instructions when trying to compile a large WASM program, instead of needing to remove `todo!` statements one by one.
I haven't covered all MInst instructions, only the ones that are the most likely to be used.

Add stubs for missing instruction emits

---

ci/zkasm-result.py
pyproject.toml

This should make the code safer and easier to read.
To verify the types you can run:
```bash
pdm run mypy
```

Add type annotations to zkasm-result.py

---

ci/test-all-zkasm.sh
ci/test-zkasm.sh
tests/zkasm/run-tests-zkasm.js

This makes it easier to use this script in the Rust runner

Use absolute paths in run-tests-zkasm.js

---

tests/zkasm/run-tests-zkasm.js

Docs try to follow [JSDoc](https://jsdoc.app) conventions to give hints on types.

docs: add some docs to `run-tests-zkasm.js`

---

cranelift/filetests/Cargo.toml

Merging upstream in #219 has bumped the workspace version from 16 to 19. As a result, `Module`, `Store`, and others are not exported anymore by `wasmtime` with the currently enabled features. To fix this the feature `runtime` is enabled:
- [why it must be enabled](https://github.com/bytecodealliance/wasmtime/blob/120e6b23950292c60b9e2d70204953e8decd6f4a/crates/wasmtime/src/lib.rs#L267-L268)
- [feature description](https://github.com/bytecodealliance/wasmtime/blob/120e6b23950292c60b9e2d70204953e8decd6f4a/crates/wasmtime/Cargo.toml#L172-L173)
The latest verions of wasmtime on [docs.rs](https://docs.rs/wasmtime/17.0.1/wasmtime/index.html) is 17.0.1, so not everything there applies to our `main` branch which is at version 19.
See [this …

fix: test compilation

---

cranelift/filetests/src/zkasm_runner.rs

This PR customized the path to NPM that we use on the Windows platform.
It is inspired by https://github.com/oscartbeaumont/rspc/blob/03240ddca56dc5a473a8652296f648c2e1d3987b/crates/create-rspc-app/src/post_gen.rs#L48

Fix npm run on Windows

---

tests/zkasm/package.json
tests/zkasm/run-tests-zkasm.js

Uses `yargs` to handle command line arguments and build a CLI. No changes in behavior.
It is now possible to show docs with `node ./run-tests-zkasm.js --help` which prints:
```
run-tests-zkasm.js <path> [outfile]
the default command runs zkASM tests
Positionals:
path     The zkASM file to run or a directory to search for zkASM files.
[string]
outfile  If provided, results are written to this file. Otherwise they are
printed to stdout.                                           [string]
Options:
--help     Show help                                                 [boolean]
--version  Show version number                                       [boolean]
```
- Make usage of the script easier, for example when running it manually during development.
- Facilitate handling of command line options …

feat(run-tests-zkasm.js): use yargs to build CLI

---

tests/zkasm/assert.js
tests/zkasm/assert_helper.js
tests/zkasm/package-lock.json
tests/zkasm/run-tests-zkasm.js

This PR adds few helper functions:
``assert_eq``, ``assert_neq``, ``assert_dump``. Filetest infra not ready yet, so I didn't change old asserts to new ones. Should I do it before merge or it can be done after? Or I should add ``.zkasm`` file somewhere to make testing this helper easy outside my machine?

[Filetests]: Add assert helper function

---

cranelift/filetests/src/lib.rs
cranelift/filetests/src/zkasm_runner.rs

This PR makes the necessary fields public and adds docstrings.
This should address https://github.com/near/wasmtime/issues/239 and make https://github.com/near/wasmtime/issues/237 easier

Make zkasm_runner public

---

cranelift/filetests/src/zkasm_runner.rs
tests/zkasm/package.json

This functionality will be used to add a subcommand to  `analyze-zkasm` which facilitates running instrumented zkASM.
- Factors out functionality in `zkasm_runner` to make it reusable.
- Adds `profile_zkasm[_path]` functions and tests them.
Can be reviewed commit-by-commit.

feat(bench): run profiling from `zkasm_runner`
